group_name: easy_multimodal
configs:
  - config_descr: Mixture_of_Normal_2d
    posterior_type: Mixture
    runs: 3
    num_samples: 2000
    num_chains: 4
    base_random_seed: 42
    varying_attribute: mu
    varying_values:
      - [3, 3]
      - [20, 50]
    varying_component: 1
    component_types:
      - MvNormal
      - MvNormal
    component_params:
      - mu: [0, 0]
        cov:
          - [1.0, 0.5]
          - [0.5, 1.0]
      - cov:
          - [2.0, 0.3]
          - [0.3, 2.0]
    weights: [0.7, 0.3]
    init_scheme: thesis_scheme
