group_name: Only_attr
configs:

  - config_descr: Vary_only_Correlation
    posterior_type: MvNormal
    varying_attribute: correlation
    varying_values: [0.0, 0.3, 0.5, 0.9, 0.95, 0.99]
    mu: ZERO_2
    cov: ID_2 

  - config_descr: Vary_only_Dimension
    posterior_type: MvNormal
    varying_attribute: dimension
    varying_values: [2, 3, 5, 8, 15, 30]
    mu: ZERO_30
    cov: ID_30

  - config_descr: Varying_only_Tails
    posterior_type: MvStudentT
    varying_attribute: nu
    varying_values: [2.1, 2.5, 3, 4, 10, 50]
    scale: ID_2
    mu: ZERO_2

  - config_descr: Varying_only_Mode_distance
    posterior_type: Mixture
    component_types: ["MvNormal", "MvNormal"]
    component_params:
      - mu: ZERO_2
        cov: ID_2
      - mu: ZERO_2
        cov: ID_2
    weights: [0.5, 0.5]
    varying_attribute: "mm"
    varying_values: [0, 4, 6, 8, 10, 12]










