group_name: single_mv_normal
configs:
  - config_descr: Mv_normal_5d
    posterior_type: MvNormal
    num_samples: 2000
    runs: 3
    num_chains: 4
    base_random_seed: 42
    varying_attribute: mu
    varying_values:
      - [10, 10, 20, 30, 30]
    cov:
      - [1.0, 0.0, 0.0, 0.0, 0.0]
      - [0.0, 1.0, 0.0, 0.0, 0.0]
      - [0.0, 0.0, 1.0, 0.0, 0.0]
      - [0.0, 0.0, 0.0, 1.0, 0.0]
      - [0.0, 0.0, 0.0, 0.0, 1.0]
